with CTE as (

select    
    TO_TIMESTAMP(STARTED_AT) as STARTED_AT, 
    DATE(STARTED_AT) as DATE_STARTED_AT,
    HOUR(TO_TIMESTAMP(STARTED_AT)) as HOUR_STARTED_AT,
    WEEK(TO_TIMESTAMP(STARTED_AT)) as WEEK_STARTED_AT,
    DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)) as DAOFWEEK_STARTED_AT,
    DAYNAME(TO_TIMESTAMP(STARTED_AT)) as DAYNAME_STARTED_AT,
    CASE
    WHEN DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)) >0 and DAYOFWEEK(TO_TIMESTAMP(STARTED_AT)) <6 
    THEN 'BUSINESSDAY' 
    ELSE 'WEEKEND'
    END as DAYTYPE,
    MONTH((TO_TIMESTAMP(STARTED_AT))) AS MONTH_STARTED_AT,
    CASE WHEN MONTH((TO_TIMESTAMP(STARTED_AT))) IN ('12','1','2')THEN 'WINTER'
        WHEN MONTH((TO_TIMESTAMP(STARTED_AT))) IN ('3','4','5') THEN 'SPRING'
        WHEN MONTH((TO_TIMESTAMP(STARTED_AT))) IN ('6','7','8') THEN 'SUMMMER'
        ELSE 'AUTUMN' 
        END AS SEASON_STARTED_AT,
    MONTHNAME((TO_TIMESTAMP(STARTED_AT))) AS MONTHNAME_STARTED_AT
from {{ source('demo', 'bike') }}
where STARTED_AT != 'started_at'

)


select
*
from CTE